// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UsersId } from './Users';

/** Identifier type for public.addresses */
export type AddressesId = string & { __brand: 'public.addresses' };

/** Represents the table public.addresses */
export default interface Addresses {
  id: AddressesId;

  userId: UsersId;

  street: string;

  city: string;

  state: string;

  postalCode: string;

  country: string;

  isDefault: boolean;

  createdAt: Date;

  updatedAt: Date;
}

/** Represents the initializer for the table public.addresses */
export interface AddressesInitializer {
  id: AddressesId;

  userId: UsersId;

  street: string;

  city: string;

  state: string;

  postalCode: string;

  country: string;

  /** Default value: false */
  isDefault?: boolean;

  /** Default value: CURRENT_TIMESTAMP */
  createdAt?: Date;

  updatedAt: Date;
}

/** Represents the mutator for the table public.addresses */
export interface AddressesMutator {
  id?: AddressesId;

  userId?: UsersId;

  street?: string;

  city?: string;

  state?: string;

  postalCode?: string;

  country?: string;

  isDefault?: boolean;

  createdAt?: Date;

  updatedAt?: Date;
}
