// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.categories */
export type CategoriesId = string & { __brand: 'public.categories' };

/** Represents the table public.categories */
export default interface Categories {
  id: CategoriesId;

  name: string;

  description: string | null;

  createdAt: Date;

  updatedAt: Date;
}

/** Represents the initializer for the table public.categories */
export interface CategoriesInitializer {
  id: CategoriesId;

  name: string;

  description?: string | null;

  /** Default value: CURRENT_TIMESTAMP */
  createdAt?: Date;

  updatedAt: Date;
}

/** Represents the mutator for the table public.categories */
export interface CategoriesMutator {
  id?: CategoriesId;

  name?: string;

  description?: string | null;

  createdAt?: Date;

  updatedAt?: Date;
}
