// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { OrdersId } from './Orders';
import type { UsersId } from './Users';
import type { default as DeliveryStatus } from './DeliveryStatus';

/** Identifier type for public.deliveries */
export type DeliveriesId = string & { __brand: 'public.deliveries' };

/** Represents the table public.deliveries */
export default interface Deliveries {
  id: DeliveriesId;

  orderId: OrdersId;

  deliveryPersonId: UsersId;

  status: DeliveryStatus;

  startTime: Date | null;

  endTime: Date | null;

  notes: string | null;

  latitude: number | null;

  longitude: number | null;

  createdAt: Date;

  updatedAt: Date;
}

/** Represents the initializer for the table public.deliveries */
export interface DeliveriesInitializer {
  id: DeliveriesId;

  orderId: OrdersId;

  deliveryPersonId: UsersId;

  /** Default value: 'ASSIGNED'::"DeliveryStatus" */
  status?: DeliveryStatus;

  startTime?: Date | null;

  endTime?: Date | null;

  notes?: string | null;

  latitude?: number | null;

  longitude?: number | null;

  /** Default value: CURRENT_TIMESTAMP */
  createdAt?: Date;

  updatedAt: Date;
}

/** Represents the mutator for the table public.deliveries */
export interface DeliveriesMutator {
  id?: DeliveriesId;

  orderId?: OrdersId;

  deliveryPersonId?: UsersId;

  status?: DeliveryStatus;

  startTime?: Date | null;

  endTime?: Date | null;

  notes?: string | null;

  latitude?: number | null;

  longitude?: number | null;

  createdAt?: Date;

  updatedAt?: Date;
}
