// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.DeliveryStatus */
enum DeliveryStatus {
  ASSIGNED = 'ASSIGNED',
  PICKED_UP = 'PICKED_UP',
  IN_TRANSIT = 'IN_TRANSIT',
  DELIVERED = 'DELIVERED',
  FAILED = 'FAILED',
  RESCHEDULED = 'RESCHEDULED',
};

export default DeliveryStatus;
