// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UsersId } from './Users';
import type { default as OrderStatus } from './OrderStatus';
import type { AddressesId } from './Addresses';
import type { default as PaymentMethod } from './PaymentMethod';
import type { default as PaymentStatus } from './PaymentStatus';

/** Identifier type for public.orders */
export type OrdersId = string & { __brand: 'public.orders' };

/** Represents the table public.orders */
export default interface Orders {
  id: OrdersId;

  userId: UsersId;

  status: OrderStatus;

  total: string;

  addressId: AddressesId;

  paymentMethod: PaymentMethod;

  paymentStatus: PaymentStatus;

  createdAt: Date;

  updatedAt: Date;
}

/** Represents the initializer for the table public.orders */
export interface OrdersInitializer {
  id: OrdersId;

  userId: UsersId;

  /** Default value: 'PENDING'::"OrderStatus" */
  status?: OrderStatus;

  total: string;

  addressId: AddressesId;

  paymentMethod: PaymentMethod;

  /** Default value: 'PENDING'::"PaymentStatus" */
  paymentStatus?: PaymentStatus;

  /** Default value: CURRENT_TIMESTAMP */
  createdAt?: Date;

  updatedAt: Date;
}

/** Represents the mutator for the table public.orders */
export interface OrdersMutator {
  id?: OrdersId;

  userId?: UsersId;

  status?: OrderStatus;

  total?: string;

  addressId?: AddressesId;

  paymentMethod?: PaymentMethod;

  paymentStatus?: PaymentStatus;

  createdAt?: Date;

  updatedAt?: Date;
}
