// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { OrdersId } from './Orders';
import type { ProductsId } from './Products';

/** Identifier type for public.order_items */
export type OrderItemsId = string & { __brand: 'public.order_items' };

/** Represents the table public.order_items */
export default interface OrderItems {
  id: OrderItemsId;

  orderId: OrdersId;

  productId: ProductsId;

  quantity: number;

  price: string;

  createdAt: Date;

  updatedAt: Date;
}

/** Represents the initializer for the table public.order_items */
export interface OrderItemsInitializer {
  id: OrderItemsId;

  orderId: OrdersId;

  productId: ProductsId;

  quantity: number;

  price: string;

  /** Default value: CURRENT_TIMESTAMP */
  createdAt?: Date;

  updatedAt: Date;
}

/** Represents the mutator for the table public.order_items */
export interface OrderItemsMutator {
  id?: OrderItemsId;

  orderId?: OrdersId;

  productId?: ProductsId;

  quantity?: number;

  price?: string;

  createdAt?: Date;

  updatedAt?: Date;
}
