// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.PaymentMethod */
enum PaymentMethod {
  CREDIT_CARD = 'CREDIT_CARD',
  DEBIT_CARD = 'DEBIT_CARD',
  BANK_TRANSFER = 'BANK_TRANSFER',
  CASH_ON_DELIVERY = 'CASH_ON_DELIVERY',
};

export default PaymentMethod;
