// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.PaymentStatus */
enum PaymentStatus {
  PENDING = 'PENDING',
  PAID = 'PAID',
  FAILED = 'FAILED',
  REFUNDED = 'REFUNDED',
};

export default PaymentStatus;
