// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { CategoriesId } from './Categories';

/** Identifier type for public.products */
export type ProductsId = string & { __brand: 'public.products' };

/** Represents the table public.products */
export default interface Products {
  id: ProductsId;

  name: string;

  description: string;

  price: string;

  stockQuantity: number;

  minimumStock: number;

  image: string | null;

  oilType: string;

  source: string;

  organic: boolean;

  coldPressed: boolean;

  volumeInLiters: string;

  categoryId: CategoriesId;

  createdAt: Date;

  updatedAt: Date;
}

/** Represents the initializer for the table public.products */
export interface ProductsInitializer {
  id: ProductsId;

  name: string;

  description: string;

  price: string;

  stockQuantity: number;

  /** Default value: 10 */
  minimumStock?: number;

  image?: string | null;

  oilType: string;

  source: string;

  /** Default value: false */
  organic?: boolean;

  /** Default value: false */
  coldPressed?: boolean;

  volumeInLiters: string;

  categoryId: CategoriesId;

  /** Default value: CURRENT_TIMESTAMP */
  createdAt?: Date;

  updatedAt: Date;
}

/** Represents the mutator for the table public.products */
export interface ProductsMutator {
  id?: ProductsId;

  name?: string;

  description?: string;

  price?: string;

  stockQuantity?: number;

  minimumStock?: number;

  image?: string | null;

  oilType?: string;

  source?: string;

  organic?: boolean;

  coldPressed?: boolean;

  volumeInLiters?: string;

  categoryId?: CategoriesId;

  createdAt?: Date;

  updatedAt?: Date;
}
