// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UsersId } from './Users';
import type { ProductsId } from './Products';

/** Identifier type for public.reviews */
export type ReviewsId = string & { __brand: 'public.reviews' };

/** Represents the table public.reviews */
export default interface Reviews {
  id: ReviewsId;

  userId: UsersId;

  productId: ProductsId;

  rating: number;

  comment: string | null;

  createdAt: Date;

  updatedAt: Date;
}

/** Represents the initializer for the table public.reviews */
export interface ReviewsInitializer {
  id: ReviewsId;

  userId: UsersId;

  productId: ProductsId;

  rating: number;

  comment?: string | null;

  /** Default value: CURRENT_TIMESTAMP */
  createdAt?: Date;

  updatedAt: Date;
}

/** Represents the mutator for the table public.reviews */
export interface ReviewsMutator {
  id?: ReviewsId;

  userId?: UsersId;

  productId?: ProductsId;

  rating?: number;

  comment?: string | null;

  createdAt?: Date;

  updatedAt?: Date;
}
