// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.UserRole */
enum UserRole {
  ADMIN = 'ADMIN',
  CUSTOMER = 'CUSTOMER',
  DELIVERY_PERSON = 'DELIVERY_PERSON',
}

export default UserRole;
