// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { default as UserRole } from './UserRole';

/** Identifier type for public.users */
export type UsersId = string & { __brand: 'public.users' };

/** Represents the table public.users */
export default interface Users {
  id: UsersId;

  email: string;

  password: string;

  firstName: string;

  lastName: string;

  phone: string | null;

  role: UserRole;

  createdAt: Date;

  updatedAt: Date;
}

/** Represents the initializer for the table public.users */
export interface UsersInitializer {
  id: UsersId;

  email: string;

  password: string;

  firstName: string;

  lastName: string;

  phone?: string | null;

  /** Default value: 'CUSTOMER'::"UserRole" */
  role?: UserRole;

  /** Default value: CURRENT_TIMESTAMP */
  createdAt?: Date;

  updatedAt: Date;
}

/** Represents the mutator for the table public.users */
export interface UsersMutator {
  id?: UsersId;

  email?: string;

  password?: string;

  firstName?: string;

  lastName?: string;

  phone?: string | null;

  role?: UserRole;

  createdAt?: Date;

  updatedAt?: Date;
}
